language: node_js
node_js:
- '8'
- '6'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
script:
- yarn lint
- yarn test
- yarn build
after_success:
- yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
